name: CI


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # For release creation we need to use the token
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if merge commit (early exit for non-merge pushes to main)
        id: check_merge
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          # Check if this is a merge commit (has more than one parent) OR commit message indicates a PR merge
          if [ $(git rev-list --count --merges HEAD^..HEAD) -gt 0 ] || git log -1 --pretty=%B | grep -qE "(Merge pull request|Merge branch|\(#[0-9]+\))" ; then
            echo "is_merge=true" >> $GITHUB_OUTPUT
            echo "✅ This is a merge commit, continuing with build and release"
          else
            echo "is_merge=false" >> $GITHUB_OUTPUT
            echo "❌ This is not a merge commit, skipping build and release"
            exit 0
          fi

      - name: Set up Node.js
        if: github.event_name == 'pull_request' || (github.ref == 'refs/heads/main' && github.event_name == 'push' && steps.check_merge.outputs.is_merge == 'true')
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Install dependencies
        if: github.event_name == 'pull_request' || (github.ref == 'refs/heads/main' && github.event_name == 'push' && steps.check_merge.outputs.is_merge == 'true')
        run: yarn install --frozen-lockfile

      - name: Build plugin
        if: github.event_name == 'pull_request' || (github.ref == 'refs/heads/main' && github.event_name == 'push' && steps.check_merge.outputs.is_merge == 'true')
        run: yarn build

      - name: Run tests
        if: github.event_name == 'pull_request' || (github.ref == 'refs/heads/main' && github.event_name == 'push' && steps.check_merge.outputs.is_merge == 'true')
        run: yarn test
        continue-on-error: true

      - name: Create Release with Commit Hash
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && steps.check_merge.outputs.is_merge == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/create-release.sh